### ISSUE TITLE
Natron 2.3.14 'thisGroup' python function not working anymore

### ISSUE THREAD

**Issue by fabiof17** [NatronGitHub/Natron#294]
### Versions

* **Natron version/commit** : (2.3.14 snapshot)
* **OS version:** Linux Mint 19

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/dcdfecd6982eddedd4a2a24ffbdb91353fa1242a

**Comment by devernay** [comment]
Fabrice, can you please check again and report?

**Comment by fabiof17** [comment]
I'll check by this evening (in about 3 hours).

**Comment by fabiof17** [comment]
Latest snapshot is still the one from 2018-07-16, so still not working.

2018-07-20 17:06 GMT+02:00 Fabrice Fernandez <fabiof17pro@gmail.com>:

**Comment by devernay** [comment]
Get the release from GitHub (release tab) or sourceforgeLe 20 juil. 2018 20:01, fabiof17 <notifications@github.com> a écrit :Latest snapshot is still the one from 2018-07-16, so still not working.

2018-07-20 17:06 GMT+02:00 Fabrice Fernandez <fabiof17pro@gmail.com>:

**Comment by fabiof17** [comment]
Tested and working 👍 (Linux)

2018-07-20 20:47 GMT+02:00 Frédéric Devernay <notifications@github.com>:
