### ISSUE TITLE
Crash when writing an image >= 12K

### ISSUE THREAD

**Issue by thunders82** [NatronGitHub/Natron#456]
### Problem

Natron is crashing when rendering an image >= than 12K

**Expected behavior:** 

I expect no crash

**Actual behavior:** 

It crashes

### Steps to Reproduce

1. Set a new project with a resolution of 12000x12000
2. Create a "constant"
3. Connect it to a "write" node
4. Set the output path and press "render"

* test12K.ntp is attached (just need to rename [test12k.txt](https://github.com/NatronGitHub/Natron/files/4177803/test12k.txt) to .ntp)

### Versions

It's happening with binaries 2.3.15 RC15 and 2.3.14. And same if I compile with the latest sources from today.

* **OS version:** 
Linux - Ubuntu 18.04

* **Shell output:**

> Natron Version 2.3.15
> Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
> >>>Use the --help or -h option to print usage.<<<
> Fontconfig configuration file /mnt/work/Dev/Tools/Natron_git/Natron/App/../Resources/etc/fonts does not exist, not setting FONTCONFIG_PATH 
> Found OpenGL Renderer: GeForce GTX 1080 Ti/PCIe/SSE2 , Vendor: NVIDIA Corporation , OpenGL Version: 4.6.0 NVIDIA 418.39 , Max. Texture Size 32768 ,Max GPU Memory: "0 byte(s)" 
> fontID= 0 families= ("Droid Sans") 
> fontID= 1 families= ("Droid Sans") 
> Setting application font to  "Droid Sans" 11 
> ... found "Droid Sans" available styles: 
> "Droid Sans" "Bold" 
> "Droid Sans" "Regular" 
> "Droid Sans" "Bold Oblique" 
> "Droid Sans" "Oblique" 
> Not an exact match, got:  "Droid Sans" 11 
> Building Fontconfig fonts... 
> Fontconfig fonts built 
> Load OFX Plugins... 
> Load OFX Plugins: prepend bundled plugins dir /mnt/work/Dev/Tools/Natron_git/Natron/Plugins/OFX/Natron 
> Load OFX Plugins: reading cache file "/home/geoffrey/.cache/INRIA/Natron/OFXLoadCache/OFXCache_2.3.15_Devel_0.xml" 
> Load OFX Plugins: reading cache file... done! 
> Load OFX Plugins: plugin path is "/mnt/work/Dev/Tools/Natron_git/Natron/Plugins/OFX/Natron" "/usr/OFX/Plugins" "/usr/OFX/Natron" "/usr/OFX/Nuke"  
> Load OFX Plugins: scan plugins... 
> Load OFX Plugins: scan plugins... done! 
> Load OFX Plugins... done! 
> templatesSearchPath:  ("/mnt/work/Dev/Tools/Natron_git/Natron/Plugins/PyPlugs", "/home/geoffrey/.Natron", "/usr/share/Natron/Plugins") 
> Info: init.py script not loaded (this is not an error)
> Info: initGui.py script not loaded (this is not an error)
> templatesSearchPath:  ("/mnt/work/Dev/Tools/Natron_git/Natron/Plugins/PyPlugs", "/home/geoffrey/.Natron", "/usr/share/Natron/Plugins") 
> Loading project: /home/geoffrey/.local/share/INRIA/Natron/Autosaves/Untitled.ntp.autosave.12686924125542583281
> Caught segmentation fault (SIGSEGV) from thread Parallel render thread (0x7f8d3400c220)(0x7f8d3400c210), faulty address is 0x7f8d6f697a6d from 0x7f8a3881b000
> Backtrace:
> [Frame 1]: /lib/x86_64-linux-gnu/libc.so.6(+0x16ca6d) [0x7f8d6f697a6d]
> [Frame 2]: /lib/x86_64-linux-gnu/libc.so.6(+0x16ca6d) [0x7f8d6f697a6d]
> [Frame 3]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x76576) [0x7f8d423ec576]
> [Frame 4]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x73368) [0x7f8d423e9368]
> [Frame 5]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x191b50) [0x7f8d42507b50]
> [Frame 6]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x74432) [0x7f8d423ea432]
> [Frame 7]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x7a5f0) [0x7f8d423f05f0]
> [Frame 8]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x83e64) [0x7f8d423f9e64]
> [Frame 9]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x86cd5) [0x7f8d423fccd5]
> [Frame 10]: /usr/OFX/Plugins/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x1a70e9) [0x7f8d4251d0e9]
> [Frame 11]: ./App/Natron(_ZN3OFX4Host11ImageEffect8Instance9mainEntryEPKcPKvPNS0_8Property3SetES9_+0xe4) [0x55d1948012b4]
> [Frame 12]: ./App/Natron(_ZN6Natron22OfxImageEffectInstance9mainEntryEPKcPKvPN3OFX4Host8Property3SetES9_+0x4b) [0x55d19452c11b]
> [Frame 13]: ./App/Natron(_ZN3OFX4Host11ImageEffect8Instance12renderActionEdRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK8OfxRectI9OfxPointDbbbPvbiiRKNS3_4listIS8_SaIS8_EEE+0x4cd) [0x55d1948082ed]
> [Frame 14]: ./App/Natron(_ZN6Natron17OfxEffectInstance6renderERKNS_14EffectInstance16RenderActionArgsE+0x478) [0x55d19450f718]
> [Frame 15]: ./App/Natron(_ZN6Natron14EffectInstance13render_publicERKNS0_16RenderActionArgsE+0xff) [0x55d194314f6f]
> QSocketNotifier: Invalid socket 35 and type 'Read', disabling...
> Caught segmentation fault (SIGSEGV) from thread Main(0x55d196efb3f0), faulty address is 0x7f8d712c61a4 from 0

**Comment by thunders82** [comment]
Hi,
I was wondering if any body managed to reproduce the issue and if there is any more tests you'd like me to run on my side ? 

Thank you

**Comment by rodlie** [comment]
I can confirm the issue, also try loading an 12k image.

Render 12k image:
```
1  OFX::PixelCopierUnPremult<float, 4, 1, float, 4, 1>::multiThreadProcessImages(OfxRectI const&, OfxPointD const&)                                                                                                                                                                                                                                                                                                                                                                             0x7fffdf13c10c 
2  OFX::PixelProcessor::multiThreadFunction(unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                                                                                                                                         0x7fffdf12c1cf 
3  Natron::(anonymous namespace)::threadFunctionWrapper                                                                                                                                                                                                                                                                                                                                                                                                        OfxHost.cpp                 1234 0x201bbca      
4  boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>::operator()<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list1<unsigned int const&>>                                                                                               bind.hpp                    517  0x2023d2d      
5  boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>::operator()<unsigned int>                                                                                                     bind_template.hpp           47   0x202353c      
6  QtConcurrent::MappedEachKernel<__gnu_cxx::__normal_iterator<unsigned int const *, std::vector<unsigned int>>, boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>>::runIteration  qtconcurrentmapkernel.h     180  0x20231ad      
7  QtConcurrent::MappedEachKernel<__gnu_cxx::__normal_iterator<unsigned int const *, std::vector<unsigned int>>, boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>>::runIterations qtconcurrentmapkernel.h     190  0x2023230      
8  QtConcurrent::IterateKernel<__gnu_cxx::__normal_iterator<unsigned int const *, std::vector<unsigned int>>, int>::forThreadFunction                                                                                                                                                                                                                                                                                                                          qtconcurrentiteratekernel.h 263  0x202378e      
9  QtConcurrent::IterateKernel<__gnu_cxx::__normal_iterator<unsigned int const *, std::vector<unsigned int>>, int>::threadFunction                                                                                                                                                                                                                                                                                                                             qtconcurrentiteratekernel.h 225  0x20233a8      
10 QtConcurrent::ThreadEngineBase::run()                                                                                                                                                                                                                                                                                                                                                                                                                                                        0x7ffff4524fbd 
11 QThreadPoolThread::run()                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0x7ffff452703a 
12 ??                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           0x7ffff45335dc 
13 start_thread                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0x7ffff402a684 
14 clone                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0x7ffff32a2eed 
```

Load 12k PNG:
```
Natron: ../../Natron/Engine/OfxClipInstance.cpp:1175: bool Natron::OfxClipInstance::getOutputImageInternal(const string*, const Natron::ImageBitDepthEnum*, OFX::Host::ImageEffect::Image**, OFX::Host::ImageEffect::Texture**): Assertion `nComps == (int)outputImage->getComponentsCount()' failed.
```
```
1   raise                                                                                                                                                 0x7ffff31d13f8 
2   abort                                                                                                                                                 0x7ffff31d2ffa 
3   __assert_fail_base                                                                                                                                    0x7ffff31c9c17 
4   __assert_fail                                                                                                                                         0x7ffff31c9cc2 
5   Natron::OfxClipInstance::getOutputImageInternal                                                                      OfxClipInstance.cpp         1175 0x2410d0e      
6   Natron::OfxClipInstance::getImagePlaneInternal                                                                       OfxClipInstance.cpp         807  0x240f057      
7   Natron::OfxClipInstance::getImage                                                                                    OfxClipInstance.cpp         740  0x240ee89      
8   OFX::Host::ImageEffect::clipGetImage                                                                                 ofxhImageEffect.cpp         3249 0x246a72e      
9   OFX::Clip::fetchImage(double)                                                                                                                         0x7fffdd2838bb 
10  OFX::IO::GenericReaderPlugin::render(OFX::RenderArguments const&)                                                                                     0x7fffdd22a1c8 
11  OFX::Private::mainEntryStr(const char *, void const *, OfxPropertySetStruct *, OfxPropertySetStruct *, const char *)                                  0x7fffdd28b088 
12  OFX::Host::ImageEffect::Instance::mainEntry                                                                          ofxhImageEffect.cpp         954  0x245fdf6      
13  Natron::OfxImageEffectInstance::mainEntry                                                                            OfxImageEffectInstance.cpp  157  0x2024a00      
14  OFX::Host::ImageEffect::Instance::renderAction                                                                       ofxhImageEffect.cpp         1465 0x2461d4c      
15  Natron::OfxEffectInstance::render                                                                                    OfxEffectInstance.cpp       2106 0x2003702      
16  Natron::ReadNode::render                                                                                             ReadNode.cpp                1418 0x20ebf58      
17  Natron::EffectInstance::render_public                                                                                EffectInstance.cpp          3745 0x1cdd3e5      
18  Natron::EffectInstance::Implementation::renderHandler                                                                EffectInstance.cpp          2698 0x1cd6999      
19  Natron::EffectInstance::Implementation::tiledRenderingFunctor                                                        EffectInstance.cpp          2375 0x1cd3ad1      
20  Natron::EffectInstance::renderRoIInternal                                                                            EffectInstanceRenderRoI.cpp 2022 0x1d1a6f9      
... <More>                                                                                                                                                               
```

I'm busy with work related stuff for a couple of days, will look more into this issue on Tuesday.

**Comment by thunders82** [comment]
Hi @rodlie ,

Thank you for the confirmation.

**Comment by thunders82** [comment]
HI @rodlie ,
I was wondering if you had a change to look into this one ?
Thank you

**Comment by devernay** [comment]
I just fixed it. You have to recompile the plugins. I'll launch a new linux build

**Comment by devernay** [comment]
binaries available from https://github.com/NatronGitHub/Natron/releases/tag/v2.3.15-rc18 :
https://github.com/NatronGitHub/Natron/releases/download/v2.3.15-rc18/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer.tar.xz
https://github.com/NatronGitHub/Natron/releases/download/v2.3.15-rc18/Natron-RB-2.3-202003302122-31210f8-Linux-64.tgz

**Comment by rodlie** [comment]
Windows binaries also added.

**Comment by thunders82** [comment]
Hi!
Thanks a lot for that! It's working as expected, except when I reuse an old script.
Reading an existing 'write' node or rendering an image crashes Natron : 

```
Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Py_SetPythonHome("/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..")
PYTHONPATH set to /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
Py_SetProgramName("/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron")
Py_Initialize()
PATH is /usr/local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PYTHONPATH is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_UseClassExceptionsFlag is 1
Py_FrozenFlag is 0
Py_TabcheckFlag is 0
Py_UnicodeFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DivisionWarningFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron
Py_GetPrefix is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Py_GetExecPrefix is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Py_GetProgramFullPath is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron
Py_GetPath is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages::/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/plat-linux2:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-tk:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-old:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-dynload
Py_GetPythonHome is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Python library is in /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/lib/python2.7/site-packages
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
Loading project: /mnt/work/Data/Input/Projects/190925-SAMPLE01/01_DANA_HEAD_08/02_DATA_PROCESSING/01_MODEL_RECONSTRUCTION/01_WORKSPACE/dense/0/test12k.ntp.autosave
Caught segmentation fault (SIGSEGV) from thread Parallel render thread (0x7f9390009e80)(0x7f9390009e70), faulty address is 0x7f93d77a6643 from 0x7f926cc05a10
Backtrace:
[Frame 1]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0x943) [0x7f93d77a6643]
[Frame 2]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0x943) [0x7f93d77a6643]
[Frame 3]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput19to_native_rectangleEiiiiiiNS_8TypeDescEPKvlllRSt6vectorIhSaIhEEjiii+0x7e7) [0x7f93d77bdc07]
[Frame 4]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput18to_native_scanlineENS_8TypeDescEPKvlRSt6vectorIhSaIhEEjii+0x59) [0x7f93d77bde29]
[Frame 5]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_19JpgOutput14write_scanlineEiiNS_8TypeDescEPKvl+0xbc) [0x7f93d7901a3c]
[Frame 6]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput15write_scanlinesEiiiNS_8TypeDescEPKvll+0x159) [0x7f93d77bc609]
[Frame 7]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput11write_imageENS_8TypeDescEPKvlllPFbPvfES4_+0x298) [0x7f93d77bc908]
[Frame 8]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x175932) [0x7f93e3100932]
[Frame 9]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x17ac81) [0x7f93e3105c81]
[Frame 10]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0xa95c1) [0x7f93e30345c1]
[Frame 11]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x1ca91a) [0x7f93e315591a]
[Frame 12]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance9mainEntryEPKcPKvPNS0_8Property3SetES9_+0x10c) [0x110d24c]
[Frame 13]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN6Natron22OfxImageEffectInstance9mainEntryEPKcPKvPN3OFX4Host8Property3SetES9_+0x49) [0xe444a9]
[Frame 14]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance12renderActionEdRKSsRK8OfxRectI9OfxPointDbbbPvbiiRKSt4listISsSaISsEE+0x3ed) [0x1115a4d]
[Frame 15]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN6Natron17OfxEffectInstance6renderERKNS_14EffectInstance16RenderActionArgsE+0x3c4) [0xe2aed4]
```



It's not a big deal for me but could be for other users ?
I believe you can test this behaviour with the script I attached in my original post.

Thank you,

Geoffrey

**Comment by devernay** [comment]
Did your clear the Natron cache? 
If yes, I don't see what could be the cause .
does the script you posted here crash too?

**Comment by thunders82** [comment]
I cleared all caches and it's still crashing. Yes the script I posted is crashing.
Let me know if you want me to run more tests or need more logs.

**Comment by thunders82** [comment]
Hi,
I did some more tests and merged 2 constants nodes in 'plus mode' in 12K and tried to render. Unfortunately it's crashing : 
`Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Py_SetPythonHome("/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..")
PYTHONPATH set to /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
Py_SetProgramName("/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron")
Py_Initialize()
PATH is /usr/local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PYTHONPATH is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_UseClassExceptionsFlag is 1
Py_FrozenFlag is 0
Py_TabcheckFlag is 0
Py_UnicodeFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DivisionWarningFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron
Py_GetPrefix is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Py_GetExecPrefix is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Py_GetProgramFullPath is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron
Py_GetPath is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages::/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/plat-linux2:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-tk:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-old:/home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/python2.7/lib-dynload
Py_GetPythonHome is /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/..
Python library is in /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/lib/python2.7/site-packages
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
Loading project: /mnt/work/Data/Input/Projects/190925-SAMPLE01/01_DANA_HEAD_08/02_DATA_PROCESSING/01_MODEL_RECONSTRUCTION/01_WORKSPACE/dense/0/normals.ntp.autosave
Loading project: /mnt/work/Data/Input/Projects/190925-SAMPLE01/01_DANA_HEAD_08/02_DATA_PROCESSING/01_MODEL_RECONSTRUCTION/01_WORKSPACE/dense/0/test12k.ntp.autosave
Caught segmentation fault (SIGSEGV) from thread Parallel render thread (0x7f09a80039e0)(0x7f09a80039d0), faulty address is 0x7f0ca3ab0643 from 0x7f0808014e10
Backtrace:
[Frame 1]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0x943) [0x7f0ca3ab0643]
[Frame 2]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0x943) [0x7f0ca3ab0643]
[Frame 3]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput19to_native_rectangleEiiiiiiNS_8TypeDescEPKvlllRSt6vectorIhSaIhEEjiii+0x7e7) [0x7f0ca3ac7c07]
[Frame 4]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput18to_native_scanlineENS_8TypeDescEPKvlRSt6vectorIhSaIhEEjii+0x59) [0x7f0ca3ac7e29]
[Frame 5]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_19JpgOutput14write_scanlineEiiNS_8TypeDescEPKvl+0xbc) [0x7f0ca3c0ba3c]
[Frame 6]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput15write_scanlinesEiiiNS_8TypeDescEPKvll+0x159) [0x7f0ca3ac6609]
[Frame 7]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput11write_imageENS_8TypeDescEPKvlllPFbPvfES4_+0x298) [0x7f0ca3ac6908]
[Frame 8]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x175932) [0x7f0caf50a932]
[Frame 9]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x17ac81) [0x7f0caf50fc81]
[Frame 10]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0xa95c1) [0x7f0caf43e5c1]
[Frame 11]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x1ca91a) [0x7f0caf55f91a]
[Frame 12]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance9mainEntryEPKcPKvPNS0_8Property3SetES9_+0x10c) [0x110d24c]
[Frame 13]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN6Natron22OfxImageEffectInstance9mainEntryEPKcPKvPN3OFX4Host8Property3SetES9_+0x49) [0xe444a9]
[Frame 14]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance12renderActionEdRKSsRK8OfxRectI9OfxPointDbbbPvbiiRKSt4listISsSaISsEE+0x3ed) [0x1115a4d]
[Frame 15]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/Natron(_ZN6Natron17OfxEffectInstance6renderERKNS_14EffectInstance16RenderActionArgsE+0x3c4) [0xe2aed4]
Caught segmentation fault (SIGSEGV) from thread Main(0x2bba9a0), faulty address is 0x7f0d418a7463 from 0
Backtrace:
[Frame 1]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN4QPenC1Ev+0x23) [0x7f0d418a7463]
[Frame 2]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN4QPenC1Ev+0x23) [0x7f0d418a7463]
[Frame 3]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN13QPainterStateC1Ev+0x64) [0x7f0d41877844]
[Frame 4]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(+0x3f1213) [0x7f0d418e5213]
[Frame 5]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(+0x3f9b45) [0x7f0d418edb45]
[Frame 6]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN8QPainter5beginEP12QPaintDevice+0x122) [0x7f0d4187d242]
[Frame 7]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN8QPainterC2EP12QPaintDevice+0x10a) [0x7f0d4187dd3a]
[Frame 8]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore+0xa11) [0x7f0d41792351]
[Frame 9]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(+0x43f0f5) [0x7f0d419330f5]
[Frame 10]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN14QWidgetPrivate16syncBackingStoreEv+0x88) [0x7f0d41786f98]
[Frame 11]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN7QWidget5eventEP6QEvent+0x7b0) [0x7f0d41797460]
[Frame 12]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN11QMainWindow5eventEP6QEvent+0x6b) [0x7f0d41af396b]
[Frame 13]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x7c) [0x7f0d4174b6fc]
[Frame 14]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x192) [0x7f0d41751452]
[Frame 15]: /home/geoffrey/Natron-RB-2.3-202003302122-31210f8-Linux-64-no-installer/bin/../lib/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x5b) [0x7f0d40e530bb]
`

**Comment by devernay** [comment]
These crashes happen in OpenImageIO, so they may be related to the file format you're using. Try using different file formats.

**Comment by thunders82** [comment]
Hi,
Indeed, if I switch to PNG output it works. But doesn't work with JPG nor EXR. Which is annoying. 
What should I do to make it work with EXR ? Recompile with the latest OpenImageIO ?

Thank you

**Comment by devernay** [comment]
It's probably fixed now (https://github.com/NatronGitHub/openfx-misc/commit/b3b089ebd38b0acb9ecfd190bba60a5d5984193d)

**Comment by devernay** [comment]
BTW, I hope you realize that an RGBA float image of resolution 12000x12000 occupied just over 2GiB of memory. That's why it triggered all these bugs.
You should try with the openimageio command-line tools (eg iconvert) if they can handle.
You should also try playing with the encoder options for exr:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/3778071/78749884-f6d21200-7923-11ea-8cb2-e013eb8aef0c.png">

rendering a 12K square OpenEXR on my mac with the latest snapshot works OK for me.
Here are the versions used for OpenImageIO:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/3778071/78750246-b58e3200-7924-11ea-9c94-d3316bf08eec.png">

**Comment by devernay** [comment]
get the latest snapshot from https://github.com/NatronGitHub/Natron/releases/tag/v2.3.15-rc19

**Comment by thunders82** [comment]
This new one seems to work with EXRs but the JPGs output is still not working. (not a real problem for me at the moment : 

> 
> OpenImageIO version (compiled with / running with): 2.1.12/2.1.12
> Dependent libraries:
> gif_lib 5.2.1
> libheif 1.6.2
> jpeg-turbo 2.0.4/jp62
> null 1.0
> OpenEXR 2.3.0
> libpng 1.6.37
> libraw 0.18.13-Release
> LIBTIFF Version 4.1.0
> Webp 1.1.0


I did some tests with the median filter and it seems to work. Awesome !

`BTW, I hope you realize that an RGBA float image of resolution 12000x12000 occupied just over 2GiB of memory. That's why it triggered all these bugs.`

Yes I know. I'm currently working with a 16K workflow in Nuke and would like to switch to Natron. 

On the other hand I tried a more complex script and rendered in batch mode using NatronRenderer. Unfortunately this one is crashing. The output is EXR.

> Write2 ==> Rendering started
Caught segmentation fault (SIGSEGV) from thread Parallel render thread (0x7f6ee000cf10)(0x7f6ee000cf00), faulty address is 0x7f6fc7cc56c4 from 0x7f693cbbf010
Backtrace:
[Frame 1]: /lib/x86_64-linux-gnu/libc.so.6(+0xbb6c4) [0x7f6fc7cc56c4]
[Frame 2]: /lib/x86_64-linux-gnu/libc.so.6(+0xbb6c4) [0x7f6fc7cc56c4]
[Frame 3]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0xe52) [0x7f6fbab38b52]
[Frame 4]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput19to_native_rectangleEiiiiiiNS_8TypeDescEPKvlllRSt6vectorIhSaIhEEjiii+0x7e7) [0x7f6fbab4fc07]
[Frame 5]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_113OpenEXROutput15write_scanlinesEiiiNS_8TypeDescEPKvll+0x256) [0x7f6fbaca2d86]
[Frame 6]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput11write_imageENS_8TypeDescEPKvlllPFbPvfES4_+0x298) [0x7f6fbab4e908]
[Frame 7]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x175932) [0x7f6fbe1fe932]
[Frame 8]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x17ac81) [0x7f6fbe203c81]
[Frame 9]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0xa95c1) [0x7f6fbe1325c1]
[Frame 10]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x1ca91a) [0x7f6fbe25391a]
[Frame 11]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/NatronRenderer(_ZN3OFX4Host11ImageEffect8Instance9mainEntryEPKcPKvPNS0_8Property3SetES9_+0x10c) [0xc9741c]
[Frame 12]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/NatronRenderer(_ZN6Natron22OfxImageEffectInstance9mainEntryEPKcPKvPN3OFX4Host8Property3SetES9_+0x49) [0x955949]
[Frame 13]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/NatronRenderer(_ZN3OFX4Host11ImageEffect8Instance12renderActionEdRKSsRK8OfxRectI9OfxPointDbbbPvbiiRKSt4listISsSaISsEE+0x3ed) [0xc9fc1d]
[Frame 14]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/NatronRenderer(_ZN6Natron17OfxEffectInstance6renderERKNS_14EffectInstance16RenderActionArgsE+0x3c4) [0x93c1a4]
[Frame 15]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/NatronRenderer(_ZN6Natron14EffectInstance13render_publicERKNS0_16RenderActionArgsE+0xd5) [0x7737d5]

I will rerender the same image from the interface and simplify the script to isolate the issue to come back to you later with more informations. 

Thank you again for all those improvements and help.

Geoffrey

**Comment by devernay** [comment]
Once again the issue is inside OpenImageIO, so I won't be able to help. maybe you could try pre-rendering using a diskcache node

**Comment by thunders82** [comment]
Hi,
I tried to simplify the problem but couldn't managed to isolate the issue as the crashes are really random. I can render the same script twice (within the interface or not) and have a crash or a successful render...

**Comment by devernay** [comment]
Try reducing the number of rendering threads in the preferences (ultimately, down to 1). Natron may be too thread-hungry, especially if you're on a machine with multiple cores

**Comment by devernay** [comment]
Are crashes always happening  in OIIO?

**Comment by devernay** [comment]
Also, as crazy as it may seem, once your graph is done (maybe on lores images, and if it's something that you intend to batch-execute a lot, I would strongly recommend coding it with VIPS (or pyvips in Python).
I successfully used pyvips to produce 40kx40k images which are the result of compositing several thousand images.

**Comment by thunders82** [comment]
I tried reducing de number of thread from 32 to 28 and it's still the same. I'm currently testing with -1 thread but it's taking ages... I'll report asap. 

The rendering is an EXR output and I think the error is always related to OIIO :
`Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Py_SetPythonHome("/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/..")
PYTHONPATH set to /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
Py_SetProgramName("/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron")
Py_Initialize()
PATH is /usr/local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PYTHONPATH is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages:
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_UseClassExceptionsFlag is 1
Py_FrozenFlag is 0
Py_TabcheckFlag is 0
Py_UnicodeFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DivisionWarningFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron
Py_GetPrefix is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/..
Py_GetExecPrefix is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/..
Py_GetProgramFullPath is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron
Py_GetPath is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../Plugins:/usr/local/lib/python2.7/site-packages::/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python27.zip:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7/plat-linux2:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7/lib-tk:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7/lib-old:/home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/../lib/python2.7/lib-dynload
Py_GetPythonHome is /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/..
Python library is in /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/lib/python2.7/site-packages
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
Loading project: /home/geoffrey/debug.ntp
Caught segmentation fault (SIGSEGV) from thread Parallel render thread (0x7f12080029e0)(0x7f12080029d0), faulty address is 0x7f13603a56c4 from 0x7f0c7bfbd010
Backtrace:
[Frame 1]: /lib/x86_64-linux-gnu/libc.so.6(+0xbb6c4) [0x7f13603a56c4]
[Frame 2]: /lib/x86_64-linux-gnu/libc.so.6(+0xbb6c4) [0x7f13603a56c4]
[Frame 3]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_13pvt10contiguizeEPKvilllPviiiNS_8TypeDescE+0xe52) [0x7f12c4645b52]
[Frame 4]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput19to_native_rectangleEiiiiiiNS_8TypeDescEPKvlllRSt6vectorIhSaIhEEjiii+0x7e7) [0x7f12c465cc07]
[Frame 5]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_113OpenEXROutput15write_scanlinesEiiiNS_8TypeDescEPKvll+0x256) [0x7f12c47afd86]
[Frame 6]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/../../Libraries/libOpenImageIO.so.2.1(_ZN16OpenImageIO_v2_111ImageOutput11write_imageENS_8TypeDescEPKvlllPFbPvfES4_+0x298) [0x7f12c465b908]
[Frame 7]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x175932) [0x7f12c7d0b932]
[Frame 8]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x17ac81) [0x7f12c7d10c81]
[Frame 9]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0xa95c1) [0x7f12c7c3f5c1]
[Frame 10]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx(+0x1ca91a) [0x7f12c7d6091a]
[Frame 11]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance9mainEntryEPKcPKvPNS0_8Property3SetES9_+0x10c) [0x110d24c]
[Frame 12]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron(_ZN6Natron22OfxImageEffectInstance9mainEntryEPKcPKvPN3OFX4Host8Property3SetES9_+0x49) [0xe444a9]
[Frame 13]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron(_ZN3OFX4Host11ImageEffect8Instance12renderActionEdRKSsRK8OfxRectI9OfxPointDbbbPvbiiRKSt4listISsSaISsEE+0x3ed) [0x1115a4d]
[Frame 14]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron(_ZN6Natron17OfxEffectInstance6renderERKNS_14EffectInstance16RenderActionArgsE+0x3c4) [0xe2aed4]
[Frame 15]: /home/geoffrey/Downloads/Natron-RB-2.3-202004080542-35a821c-Linux-64-no-installer/bin/Natron(_ZN6Natron14EffectInstance13render_publicERKNS0_16RenderActionArgsE+0xd5) [0xc45715]
`

I'll have a look at VIPS. I never used it.

**Comment by devernay** [comment]
Even 28 is a lot. My guess is that you dont' have 28 CPUs? You probably only have 16 (hyperthreaded) cores, right? So 16 seems like a more reasonable value. There may be a threading issue with OIIO (there have been a few in the past), and we should probably add an option to disable mutithreading in OIIO for such cases.

Also, as pointed out [here](https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html#common-workarounds), you should consider using the [DiskCache node](https://natron.readthedocs.io/en/rb-2.3/plugins/fr.inria.built-in.DiskCache.html#fr-inria-built-in-diskcache). If writing using the diskcache works, then pre-render in the cache, and then do a single-threaded execution to write the EXRs.

**Comment by thunders82** [comment]
I rendered 3 times in a row with -1 thread -> all good
I rendered 3 times in a row with 16 threads -> all good
I rendered with all the threads -> crash

So you are probably right with the multi threading issue with OIIO.

I did a quick test with all the threads and baked the diskCache (just before the write node). It worked as expected. I then rendered the Write node but it crashed again due to the multi threading... Re-rendering with -1 thread works as expected. 
Your option to disable multithreading seems a good alternative if OIIO takes time to resolve this issue.

Let me know if you need more tests from my side.

And if you don't mind... Which node is the fastest median node ? It can be gpu based. The important part is that it needs to handle big size (+/-60). 
And would it be easy to use/convert an open source nuke node within Natron ? (https://github.com/AuthorityFX/afx-nuke-plugins)

Thank you again

**Comment by devernay** [comment]
These Nuke plugins are using CUDA, and CUDA is not supported. There are several GLSL median filters that could be implemented with shadertoy, but none supports 60x60!
Honestly, I don't know what's your use case exactly, but a 60x60 median filter makes little sense to me. Do you realize it requires (almost) sorting an array with 3600 values at each pixel?
Did you consider cascading several 3x3 median filters?

**Comment by thunders82** [comment]
Yes I know. It's a really complex workflow. It's a 16k close up and I need a big frequency filtering to remove specific bands... 
The median filter node within Natron is working well and the efficiency is not too bad. I'm quite impressed to be honest. I was just wondering if I could speed it up as it's only using cpu.
I'll run some benchmark comparison with the same filtering value between Nuke and Natron.

Thank you so much for your help and efforts to make a real open source alternative to Nuke.

**Comment by devernay** [comment]
I guess you're using this for scientific needs rather than video compositing, right?
I think your best friend in this case is VIPS, and it's not that difficult to use.
On the GPU side, you ay want to take a look at Halide, but I'm not sure it can handle images that large https://halide-lang.org/

**Comment by thunders82** [comment]
Yes it's more for the usage of simple mathematical formulas and the median filter. I'll check Halide and VIPS as it sounds really interesting. Thanks for sharing this.
I'm mainly using compositing tools to workaround my lack of knowledge regarding the maths behind the median filter and it's optimisations.
